services:
  nginx:
    image: nginx:alpine
    container_name: proxy_nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app_backend
    networks:
      - red-cba
  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd-ejemplo
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - red-cba

  app_backend:
    build: .
    container_name: app-backend-ejemplo
    volumes:
      - .:/home/natalia/Proyectos/proyecto-terminal/
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - red-cba
    depends_on:
      - servidor-bd

networks:
  red-cba:
    name: red-cba-ejemplo

volumes:
  mysql-data:
    name: mysql-data